
import type { User, Task, Project } from '@/lib/types';


export const initialUsers: User[] = [
    { id: '1', name: "Super Admin", email: "admin@example.com", password: "password123", contact: "11911111111", avatar: "SA", role: "Admin", status: "Ativo" },
    { id: '2', name: "Gerente de Projeto", email: "gp@example.com", password: "password123", contact: "11922222222", avatar: "GP", role: "Gerente", status: "Ativo" },
    { id: '3', name: "Diego", email: "diego@example.com", password: "password123", contact: "11933333333", avatar: "D", role: "Membro", status: "Ativo" },
    { id: '4', name: "Ana", email: "ana@example.com", password: "password123", contact: "11944444444", avatar: "A", role: "Membro", status: "Inativo" },
    { id: '5', name: "Carlos", email: "carlos@example.com", password: "password123", contact: "11955555555", avatar: "C", role: "Gerente", status: "Ativo" },
];

export const mockTasksData: Task[] = [
    {
        id: "TSK-0001",
        project: "Projeto Alpha",
        name: "Planejamento Inicial",
        assignee: "GP",
        status: "Feito",
        priority: "Alta",
        start: new Date("2024-05-01"),
        end: new Date("2024-05-05"),
        progress: 100,
        dependencies: [],
        parentId: null,
        milestone: true,
        tags: ["Core", "Planejamento"],
        comments: [
            { user: "GP", text: "Datas ajustadas devido a novo requisito do cliente.", date: "2024-05-02T10:00:00Z" }
        ],
        baselines: [
            { name: "Plano Original", start: new Date("2024-05-01"), end: new Date("2024-05-04") }
        ]
    },
    {
        id: "TSK-0002",
        project: "Projeto Alpha",
        name: "Design da Interface",
        assignee: "DA",
        status: "Em Progresso",
        priority: "Média",
        start: new Date("2024-05-06"),
        end: new Date("2024-05-15"),
        progress: 50,
        dependencies: ["TSK-0001"],
        parentId: null,
        tags: ["UI/UX"],
    },
    {
        id: "TSK-0003",
        project: "Projeto Alpha",
        name: "Desenvolvimento do App",
        assignee: "FE",
        status: "A Fazer",
        priority: "Alta",
        start: new Date("2024-05-16"),
        end: new Date("2024-06-10"),
        progress: 0,
        dependencies: ["TSK-0002"],
        parentId: null,
    },
     {
        id: "TSK-0004",
        project: "Projeto Beta",
        name: "Pesquisa de Mercado",
        assignee: "GP",
        status: "Atrasado",
        priority: "Alta",
        start: new Date("2024-06-01"),
        end: new Date("2024-06-10"),
        progress: 80,
        dependencies: [],
        parentId: null,
        milestone: true,
    },
    {
        id: "TSK-0005",
        project: "Projeto Beta",
        name: "Desenvolvimento do Backend",
        assignee: "BE",
        status: "Em Progresso",
        priority: "Alta",
        start: new Date("2024-06-11"),
        end: new Date("2024-06-25"),
        progress: 40,
        dependencies: ["TSK-0004"],
        parentId: null,
    },
    {
        id: "TSK-0006",
        project: "Projeto Beta",
        name: "Lançamento Beta",
        assignee: "GP",
        status: "A Fazer",
        priority: "Média",
        start: new Date("2024-06-26"),
        end: new Date("2024-06-30"),
        progress: 0,
        dependencies: ["TSK-0005"],
        parentId: null,
        milestone: true,
    },
    {
        id: "TSK-0007",
        project: "Projeto Gamma",
        name: "Definição de Requisitos",
        assignee: "FE",
        status: "Feito",
        priority: "Alta",
        start: new Date("2024-07-01"),
        end: new Date("2024-07-05"),
        progress: 100,
        dependencies: [],
        parentId: null,
    },
    {
        id: "TSK-0008",
        project: "Projeto Gamma",
        name: "Prototipação",
        assignee: "UI",
        status: "Feito",
        priority: "Média",
        start: new Date("2024-07-06"),
        end: new Date("2024-07-15"),
        progress: 100,
        dependencies: ["TSK-0007"],
        parentId: null,
    },
    {
        id: "TSK-0009",
        project: "Projeto Gamma",
        name: "Testes de Usabilidade",
        assignee: "GP",
        status: "Em Progresso",
        priority: "Baixa",
        start: new Date("2024-07-16"),
        end: new Date("2024-07-20"),
        progress: 90,
        dependencies: ["TSK-0008"],
        parentId: null,
    },
     {
        id: "TSK-0010",
        project: "Projeto Delta",
        name: "Configuração de Infra",
        assignee: "GP",
        status: "Feito",
        priority: "Alta",
        start: new Date("2024-07-10"),
        end: new Date("2024-07-15"),
        progress: 100,
        dependencies: [],
        parentId: null,
    },
    {
        id: "TSK-0011",
        project: "Projeto Delta",
        name: "Desenvolvimento da API",
        assignee: "BE",
        status: "Atrasado",
        priority: "Alta",
        start: new Date("2024-07-16"),
        end: new Date("2024-07-30"),
        progress: 25,
        dependencies: ["TSK-0010"],
        parentId: null,
    },
    {
        id: "TSK-0012",
        project: "Projeto Delta",
        name: "Integração Contínua",
        assignee: "FE",
        status: "A Fazer",
        priority: "Média",
        start: new Date("2024-08-01"),
        end: new Date("2024-08-05"),
        progress: 0,
        dependencies: ["TSK-0011"],
        parentId: null,
    },
    {
        id: "TSK-0013",
        project: "Projeto Alpha",
        name: "Subtarefa de Design 1",
        assignee: "DA",
        status: "A Fazer",
        priority: "Média",
        start: new Date("2024-05-06"),
        end: new Date("2024-05-10"),
        progress: 0,
        dependencies: [],
        parentId: 'TSK-0002',
    },
     {
        id: "TSK-0014",
        project: "Projeto Alpha",
        name: "Subtarefa de Design 2",
        assignee: "DA",
        status: "A Fazer",
        priority: "Média",
        start: new Date("2024-05-11"),
        end: new Date("2024-05-15"),
        progress: 0,
        dependencies: ['TSK-0013'],
        parentId: 'TSK-0002',
    },
];

export const mockProjects: Project[] = [
    { name: 'Projeto Alpha', description: 'Desenvolvimento do novo app mobile.', budget: 50000, spent: 25000, startDate: new Date('2024-05-01'), endDate: new Date('2024-07-30'), collaborators: [{userId: '2', role: 'Gerente'}, {userId: '3', role: 'Membro'}] },
    { name: 'Projeto Beta', description: 'Campanha de lançamento para o Q3.', budget: 75000, spent: 40000, startDate: new Date('2024-06-01'), endDate: new Date('2024-08-31'), collaborators: [{userId: '5', role: 'Gerente'}] },
    { name: 'Projeto Gamma', description: 'Otimização de SEO para o site principal.', budget: 20000, spent: 18000, startDate: new Date('2024-07-01'), endDate: new Date('2024-07-31'), collaborators: [{userId: '2', role: 'Gerente'}]},
    { name: 'Projeto Delta', description: 'Migração de infraestrutura para a nuvem.', budget: 120000, spent: 30000, startDate: new Date('2024-07-10'), endDate: new Date('2024-09-30'), collaborators: [{userId: '5', role: 'Gerente'}]},
];
